name: Python application

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        poetry-version: [1.10.0, 2.1.2]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry ${{ matrix.poetry-version }}
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: View Python version
        run: |
          python --version
          pip --version
          poetry -V
          poetry --help
          poetry python list

      - name: Install dependencies
        shell: bash
        run: python -m poetry install

      - name: Test
        run: |
          poetry run python manage.py test
